sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-19mode
  - jruby-head

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org

matrix:
  allow_failures:
    - rvm: jruby-head
